### ISSUE TITLE
About moduleG.py Missing

### ISSUE THREAD

**Issue by Tsunami-Song** [Y-Xiang-hub/Bitcoin-Address-Behavior-Analysis#1]
When I run python graph_generation.py, I found that "ModuleNotFoundError: No module named 'moduleG'", and I don't know what to do next.
Can you help?

**Comment by Y-Xiang-hub** [comment]
> When I run python graph_generation.py, I found that "ModuleNotFoundError: No module named 'moduleG'", and I don't know what to do next. Can you help?

After our paper is accepted, we will upload 'moduleG', besides, it is not that complicated to reproduce our work according to our paper. Thank you for your interest in our work.
