### ISSUE TITLE
Hello,Could you please upload the raw data which are not preprocessed? Thank you very much! 

### ISSUE THREAD

**Issue by DancyDongShi** [Y-Xiang-hub/Bitcoin-Address-Behavior-Analysis#3]

**Comment by Y-Xiang-hub** [comment]
I appreciate your interest in our work, however, uploading a massive amount of raw data will violate the user agreement of GitHub. Therefore, in this repository, we provide the code to collect raw data for constructing the transaction graph in the `data_collection` folder.
